---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: liker-review-font-sans
spec:
  interval: 30s
  url: https://github.com/thmzlt/liker
  ref:
    branch: review-font-sans
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: liker-review-font-sans
spec:
  sourceRef:
    kind: GitRepository
    name: liker-review-font-sans
  interval: 30s
  prune: true
  path: "./manifests"
  postBuild:
    substitute:
      appName: liker-review-font-sans
      appSubdomain: liker-review-font-sans
      appReplicas: "1"
      color: aliceblue
      prompt: Do you like Kubernetes on review?
